### ISSUE TITLE
Clarify the project licensing

### ISSUE THREAD

**Issue by tbroyer** [nicolassmith/urlevaluator#1]
Before I start contributing, I'd like to know which license you chose for the project? Apache 2.0, Public Domain, MIT, BSD, GPL?

**Comment by nicolassmith** [comment]
Licence information is in the LICENSE.md file and it is the MIT license. Thanks for the interest!

**Comment by tbroyer** [comment]
Wow, I somehow totally missed it! Sorry for the noise.
