### ISSUE TITLE
Infinite redirect loop

### ISSUE THREAD

**Issue by duetosymmetry** [nicolassmith/urlevaluator#26]
t.co seems to give infinite redirect loops. This basically makes Twitter unusable. I'm traveling tomorrow to a conference so won't have a chance to investigate further until a week from now.

**Comment by nicolassmith** [comment]
Is this a new issue (since latest update)?

**Comment by nicolassmith** [comment]
Can you add an example URL that shows this problem?

**Comment by duetosymmetry** [comment]
This worked before and now it doesn't.

Example: http://t.co/iEguCemYmH

**Comment by duetosymmetry** [comment]
@nicolassmith is the bestest!
