### ISSUE TITLE
Add j.mp

### ISSUE THREAD

**Issue by tbroyer** [nicolassmith/urlevaluator#6]
Just clicked through a j.mp link that urlevaluator didn't detect: https://twitter.com/typekit/status/312283964322746368 (it resolved the t.co but then displayed _evaluated as &lt;the j.mp URL>_ and opened a browser (or in my case, showed the chooser to select a browser, no Short URL Evaluator in the list)

**Comment by duetosymmetry** [comment]
This is addressed in my [pull request](https://github.com/nicolassmith/urlevaluator/pull/7).
